config/routes.rb
Rails.application.routes.draw do
  get 'design_explorations/recirculation'

  get 'design_explorations/guides'

  get 'design_explorations/new_stories_menu'

  get 'design_explorations/conf_guide'

  get 'design_explorations/list_article'

  get 'design_explorations/article_2'


  root 'style_guide#index'

  get 'style_guide/index'

  get '/standard-article' => 'style_guide#typography', as: 'article'

  get '/opinion-piece' => 'style_guide#opinion', as: 'opinion'

  get '/service-post' => 'style_guide#service', as: 'service'

  get '/interview' => 'style_guide#interview', as: 'interview'

  get '/right-rail-headline-list' => 'style_guide#rr_base', as: 'rr_base'

  get '/right-rail-email-signup' => 'style_guide#rr_email_signup', as: 'rr_email_signup'

  get '/default-recirculation' => 'style_guide#recirc_default', as: 'recirc_default'

  get 'style_guide/colors'

  get 'style_guide/imagery'

  get 'style_guide/logo'

  get 'style_guide/story'

  get 'style_guide/voice'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/design_explorations_controller.rb
class DesignExplorationsController < ApplicationController
  def recirculation
  end

  def guides
    render layout: 'fake-inman'
  end

  def new_stories_menu
    render layout: 'fake-inman'
  end

  def conf_guide
    render layout: 'fake-inman'
  end

  def list_article
    render layout: 'fake-inman'
  end

  def article_2
    render layout: 'fake-inman'
  end
end

app/controllers/style_guide_controller.rb
class StyleGuideController < ApplicationController
  def index
  end

  def typography
  end

  def opinion
  end

  def service
  end

  def interview
  end

  def colors
  end

  def rr_base
  end

  def rr_email_signup
  end

  def recirc_default
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/design_explorations_helper.rb
module DesignExplorationsHelper
end

app/helpers/style_guide_helper.rb
module StyleGuideHelper
end

app/views/design_explorations/article_2.html.haml
.hat-nav
=image_tag('bwLogoInman.png', :class => "inman-logo-bw")
%p.main-headline
  Want your listing to stand out?
  %br
  Try these 5 buyer incentives
%span.lead-image
  %p.dek In a shifting market, agents will have to get creative in how they market their listings

%section
  .number-header
    1
    </br>
    A Rent Free Year
  .copy-chunk
    .chunk-intro Kirkwood Homes recently implemented a new way of motivating buyers to buy its properties.
    .chunk-body Anyone who reserves a plot will receive a voucher of £19,000 (more than $24,000 USD) — enough to cover the costs of living in the house for a whole year! The voucher can be used for a variety of costs, including carpet and flooring, curtains and blinds, land and buildings transaction tax (LBTT), legal fees and removal fees.
    .chunk-body Buyers can choose between 51 detached house floor plans that include 3- and 4-bedroom terraced homes.

%section
  .number-header
    2
    </br>
    Expensive Cars
  .copy-chunk
    .chunk-intro It has been a common gesture for builders to offer house appliances such as a dishwasher, an air conditioner or a stove, but certain builders will go even further to motivate buyers.
    .chunk-body Back in 2013, Kylemore Communities, a builder from Markham, Ontario, Canada, offered $35,000 CDN (more than $26,000 USD) toward any new BMW car with a purchase of a condo in one of their developments.
    .chunk-body Then, in 2015, Century 21 Bamber Realty, located in Calgary, Alberta, Canada, offered a brand-new Tesla car — a gift valued at more than $100,000 — to the buyer of a $2.349 million home that was listed with the brokerage.
    .chunk-body Many people question the motive for giving away big, expensive gifts, but brokerages and agents who opt for this strategy realize that the expensive gift may help prevent losing hundreds of thousands in price drops.
    .chunk-body These agents know that human psychology works as some potential buyers see these luxury gifts as something that’s worth more than a discount, even if that’s not really the case.
=image_tag("connect-ad.jpg");
%section
  .number-header
    3
    </br>
    Reward Community
  .copy-chunk
    .chunk-intro As a token of appreciation for the individuals who help protect the community and livelihood of everyone, U.S.-based homebuilder K. Hovnanian offers to cover $5,000 of the price of its homes.
    .chunk-body This incentive is open to anyone in the civil service sector, including emergency medical teams (EMTs), hospital staff, firefighters, police officers and military men and women. Other builders have also joined in and are offering discounts on house prices for service men and women around the globe.
%section
  .number-header
    4
    </br>
    $1 Houses
  .copy-chunk
    .chunk-intro There is an Italian town called Ollolai, located on the island Sardinia. In this town, there are hundreds of small houses that are currently selling for as low as 1 euro.
    .chunk-body This incentive is open to anyone in the civil service sector, including emergency medical teams (EMTs), hospital staff, firefighters, police officers and military men and women. Other builders have also joined in and are offering discounts on house prices for service men and women around the globe.
%section
  .number-header
    5
    </br>
    tacos, tacos, tacos
  .copy-chunk
    .chunk-intro Last year, Albuquerque Realtor Mike Leathers was willing to shell out $500 to the future owners of his townhome listing to compensate for the tacos of their choosing. The townhome up for grabs in Albuquerque was listed for $174,900. Five hundred dollars, that’s about 333 Taco Bell tacos.
    .chunk-body While this is just a sample of the more elaborate incentives we’ve come across, there are many other interesting incentives, including assured sales (guaranteed purchase if you decide to sell your property), shopping sprees, personalization packages, free trips to exotic locations, $3,000 Apple gift cards as well as the more conventional furniture, window coverings, credits for non-recurring closing costs, etc. and more.
    .chunk-body A little creativity is all it takes.
    =image_tag("sharing.png", :class => "fakeSharing");
=image_tag("bottom-2.jpg", :class => "fakeBottom");

app/views/design_explorations/chapters/_bitcoin-1.html.haml
%section.guides-body.chapter-1.hidden{"data-chapter" => "1"}
  %ul.page-nav
    %li Cover
    %li 2: Cryptocurrency

  %h3
    %span 1.0
    Overview


  %p Quo at agam movet, pri te duis fugit. Liber elaboraret mei id, an sit nibh voluptatum, odio discere fastidii at per. In his etiam simul constituto, at sale honestatis mea, illum mandamus vulputate nec ei. Ad nec ocurreret voluptatum, vel an dolor iudicabit.

  %p.half-width An vis agam iisque deleniti, has nulla consectetuer id. Eu sit mutat adipisci. Usu no natum dicta saperet, qui rebum dicant tibique an. Ea vix dictas inermis, et per nemore ornatus. Per ad lobortis iracundia, an tation munere impedit ius, ne tibique copiosae eam.


  .guide-progress-bar
    .read
      %p 8/72
    .unread

app/views/design_explorations/chapters/_bitcoin-2.html.haml
%section.guides-body.chapter-2.hidden{"data-chapter" => "2"}
  %ul.page-nav
    %li 1: Overview
    %li 3: Blockchain

  %h3
    %span 2.0
    Cryptocurrency


  %p Quo at agam movet, pri te duis fugit. Liber elaboraret mei id, an sit nibh voluptatum, odio discere fastidii at per. In his etiam simul constituto, at sale honestatis mea, illum mandamus vulputate nec ei. Ad nec ocurreret voluptatum, vel an dolor iudicabit.

  %p An vis agam iisque deleniti, has nulla consectetuer id. Eu sit mutat adipisci. Usu no natum dicta saperet, qui rebum dicant tibique an. Ea vix dictas inermis, et per nemore ornatus. Per ad lobortis iracundia, an tation munere impedit ius, ne tibique copiosae eam.


  .guide-progress-bar
    .read
      %p 8/72
    .unread

app/views/design_explorations/chapters/_bitcoin-3.html.haml
%section.guides-body.chapter-3.hidden{"data-chapter" => "3"}
  %ul.page-nav
    %li 2: Blockchain
    %li 4: Bitcoin

  %h3
    %span 3.0
    Blockchain

  %p.intro At its core, bitcoin is a smart currency, designed by very forward-thinking engineers. It eliminates the need for banks, gets rid of credit card fees, currency exchange fees, money transfer fees, and reduces the need for lawyers in transitions… all good things...

  %p.half-width Quo at agam movet, pri te duis fugit. Liber elaboraret mei id, an sit nibh voluptatum, odio discere fastidii at per. In his etiam simul constituto, at sale honestatis mea, illum mandamus vulputate nec ei. Ad nec ocurreret voluptatum, vel an dolor iudicabit.

  %p.half-width An vis agam iisque deleniti, has nulla consectetuer id. Eu sit mutat adipisci. Usu no natum dicta saperet, qui rebum dicant tibique an. Ea vix dictas inermis, et per nemore ornatus. Per ad lobortis iracundia, an tation munere impedit ius, ne tibique copiosae eam.

  =image_tag('chart-1.png', :class => 'guide-body-image');

  .guide-progress-bar
    .read
      %p 8/72
    .unread

app/views/design_explorations/chapters/_bitcoin-4.html.haml
%section.guides-body.chapter-4{"data-chapter" => "4"}
  %ul.page-nav
    %li 3.9: Blockchain. Summary
    %li 4.1: Bitcoin. History

  %h3
    %span 4.0
    Bitcoin

  %p.intro At its core, bitcoin is a smart currency, designed by very forward-thinking engineers. It eliminates the need for banks, gets rid of credit card fees, currency exchange fees, money transfer fees, and reduces the need for lawyers in transitions… all good things...

  %p.half-width Quo at agam movet, pri te duis fugit. Liber elaboraret mei id, an sit nibh voluptatum, odio discere fastidii at per. In his etiam simul constituto, at sale honestatis mea, illum mandamus vulputate nec ei. Ad nec ocurreret voluptatum, vel an dolor iudicabit.

  %p.half-width An vis agam iisque deleniti, has nulla consectetuer id. Eu sit mutat adipisci. Usu no natum dicta saperet, qui rebum dicant tibique an. Ea vix dictas inermis, et per nemore ornatus. Per ad lobortis iracundia, an tation munere impedit ius, ne tibique copiosae eam.

  =image_tag('chart-1.png', :class => 'guide-body-image');

  .guide-progress-bar
    .read
      %p 4/72
    .unread

app/views/design_explorations/chapters/_bitcoin-5.html.haml
%section.guides-body.chapter-5.hidden{"data-chapter" => "5"}
  %ul.page-nav
    %li 4: Bitcoin
    %li 6: Lorem Ipsum

  %h3
    %span 5.0
    Etherium


  %p Quo at agam movet, pri te duis fugit. Liber elaboraret mei id, an sit nibh voluptatum, odio discere fastidii at per. In his etiam simul constituto, at sale honestatis mea, illum mandamus vulputate nec ei. Ad nec ocurreret voluptatum, vel an dolor iudicabit.

  %p An vis agam iisque deleniti, has nulla consectetuer id. Eu sit mutat adipisci. Usu no natum dicta saperet, qui rebum dicant tibique an. Ea vix dictas inermis, et per nemore ornatus. Per ad lobortis iracundia, an tation munere impedit ius, ne tibique copiosae eam.


  .guide-progress-bar
    .read
      %p 8/72
    .unread

app/views/design_explorations/guides.html.haml
%section.guides-cover
  .left
  .right


.guides-toc.mobile-nav-hidden


  %ul.toc-wrap
    %li
      %span.close-toc-mobile.hidden close nav
      %h5.btn-guides.btn-all-guides All Guides
      %h6 01: Crypto & Real Estate
      %ul.toc
        %li.toc-item{"data-chapter" => "0"} i. cover
        %li.toc-item{"data-chapter" => "1"} 1. overview
        %li.toc-item{"data-chapter" => "2"} 2. Cryptocurrency
        %li.toc-item{"data-chapter" => "3"} 3. Blockchain
        %li.toc-item{"data-chapter" => "4", :class => "active"} 4. Bitcoin
        %li.toc-item{"data-chapter" => "5"} 5. Etherium to Doge
        %li.toc-item{"data-chapter" => "6"} 6. lorem ipsum
        %li.sponsor
          sponsored by:
          =image_tag("sponsor.png")
        %li.toc-mobile-btn.hidden show nav

      %li
        %h5.btn-guides.btn-close-guides-menu Back
        %h6 All Guides
        %ul.toc
          %li.toc-item{"data-chapter" => "0"} 01
          %li.toc-item{"data-chapter" => "1"} 02
          %li.toc-item{"data-chapter" => "2"} 03
          %li.toc-item{"data-chapter" => "3"} 04
          %li.toc-item{"data-chapter" => "4"} 05
          %li.toc-item{"data-chapter" => "5"} 06
          %li.toc-item{"data-chapter" => "6"} 07
          %li.sponsor
            sponsored by:
            =image_tag("sponsor.png");


.guides-rightSide
  = render '/partials/all-guides';
  =render "design_explorations/chapters/bitcoin-1";
  =render "design_explorations/chapters/bitcoin-2";
  =render "design_explorations/chapters/bitcoin-3";
  =render "design_explorations/chapters/bitcoin-4";
  =render "design_explorations/chapters/bitcoin-5";
  =render "design_explorations/chapters/bitcoin-6";

app/views/design_explorations/list_article.html.haml
.hat-nav
=image_tag('bwLogoInman.png', :class => "inman-logo-bw")
%p.main-headline
  Want your listing to stand out?
  %br
  Try these 5 buyer incentives
%span.lead-image
  %p.dek In a shifting market, agents will have to get creative in how they market their listings

%section
  .number-header
    1
    </br>
    A Rent Free Year
  .copy-chunk
    .chunk-intro Kirkwood Homes recently implemented a new way of motivating buyers to buy its properties.
    .chunk-body Anyone who reserves a plot will receive a voucher of £19,000 (more than $24,000 USD) — enough to cover the costs of living in the house for a whole year! The voucher can be used for a variety of costs, including carpet and flooring, curtains and blinds, land and buildings transaction tax (LBTT), legal fees and removal fees.
    .chunk-body Buyers can choose between 51 detached house floor plans that include 3- and 4-bedroom terraced homes.

%section
  .number-header
    2
    </br>
    Expensive Cars
  .copy-chunk
    .chunk-intro It has been a common gesture for builders to offer house appliances such as a dishwasher, an air conditioner or a stove, but certain builders will go even further to motivate buyers.
    .chunk-body Back in 2013, Kylemore Communities, a builder from Markham, Ontario, Canada, offered $35,000 CDN (more than $26,000 USD) toward any new BMW car with a purchase of a condo in one of their developments.
    .chunk-body Then, in 2015, Century 21 Bamber Realty, located in Calgary, Alberta, Canada, offered a brand-new Tesla car — a gift valued at more than $100,000 — to the buyer of a $2.349 million home that was listed with the brokerage.
    .chunk-body Many people question the motive for giving away big, expensive gifts, but brokerages and agents who opt for this strategy realize that the expensive gift may help prevent losing hundreds of thousands in price drops.
    .chunk-body These agents know that human psychology works as some potential buyers see these luxury gifts as something that’s worth more than a discount, even if that’s not really the case.
=image_tag("connect-ad.jpg");
%section
  .number-header
    3
    </br>
    Reward Community
  .copy-chunk
    .chunk-intro As a token of appreciation for the individuals who help protect the community and livelihood of everyone, U.S.-based homebuilder K. Hovnanian offers to cover $5,000 of the price of its homes.
    .chunk-body This incentive is open to anyone in the civil service sector, including emergency medical teams (EMTs), hospital staff, firefighters, police officers and military men and women. Other builders have also joined in and are offering discounts on house prices for service men and women around the globe.
%section
  .number-header
    4
    </br>
    $1 Houses
  .copy-chunk
    .chunk-intro There is an Italian town called Ollolai, located on the island Sardinia. In this town, there are hundreds of small houses that are currently selling for as low as 1 euro.
    .chunk-body This incentive is open to anyone in the civil service sector, including emergency medical teams (EMTs), hospital staff, firefighters, police officers and military men and women. Other builders have also joined in and are offering discounts on house prices for service men and women around the globe.
%section
  .number-header
    5
    </br>
    tacos, tacos, tacos
  .copy-chunk
    .chunk-intro Last year, Albuquerque Realtor Mike Leathers was willing to shell out $500 to the future owners of his townhome listing to compensate for the tacos of their choosing. The townhome up for grabs in Albuquerque was listed for $174,900. Five hundred dollars, that’s about 333 Taco Bell tacos.
    .chunk-body While this is just a sample of the more elaborate incentives we’ve come across, there are many other interesting incentives, including assured sales (guaranteed purchase if you decide to sell your property), shopping sprees, personalization packages, free trips to exotic locations, $3,000 Apple gift cards as well as the more conventional furniture, window coverings, credits for non-recurring closing costs, etc. and more.
    .chunk-body A little creativity is all it takes.
    =image_tag("sharing.png", :class => "fakeSharing");
=image_tag("newBottom.jpg", :class => "fakeBottom");

app/views/design_explorations/recirculation.html.haml
%h1 DesignExplorations#recirculation
%p Find me in app/views/design_explorations/recirculation.html.haml

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    //%meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %title InmanDesign
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body{"data-action" => "#{controller.action_name}", "data-controller" => "#{controller.controller_path}"}
    .content
      = yield

app/views/layouts/fake-inman.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title InmanDesign
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body{"data-action" => "#{controller.action_name}", "data-controller" => "#{controller.controller_path}"}
    = render "/partials/fake-inman-nav"
    .content
      = yield
    .below-guides
      =image_tag("guides-below.jpg");

app/views/partials/_all-guides.html.haml
#all-guides
  -#%h5.btn-guides.btn-close-guides-menu Back
  %h4
    Inman Guides /
    %span All

  %ul.guides-list
    %li
      .progress-indicator.eighty
      .img
      .guide-card-title Guide Title 1
    %li
      .progress-indicator.ten
      .img
      .guide-card-title Guide Title 2
    %li
      .progress-indicator.forty
      .img
      .guide-card-title Guide Title 3
    %li
      .progress-indicator.ten
      .img
      .guide-card-title Guide Title 4
    %li
      .progress-indicator.thirty
      .img
      .guide-card-title Guide Title 5
    %li
      .progress-indicator.forty
      .img
      .guide-card-title Guide Title 6
    %li
      .progress-indicator.forty
      .img
      .guide-card-title Guide Title 7
    %li
      .progress-indicator.ten
      .img
      .guide-card-title Guide Title 8

app/views/partials/_fake-inman-nav.html.haml
.fake-inman-nav
  .top-bar
    %button.hamburger.hamburger--collapse{:type => "button"}
      %span.hamburger-box
        %span.hamburger-inner
    %h2 inman
    %span.account-btn Login
    .main-dropdown
      %ul
        %li
          Agent
        %li
          Brokerage
        %li
          Technology
        %li
          Marketing
        %li
          Tech Reviews
        %li
          Video
        %li
          Opinion

  .new-stories-nav
    %ul
      %li
        %span.close-subnav x
        %span
        New Stories
        .first-drop.drop
          %span
            .date January 30th
            %p Zillow to acquire Mortgage Lenders of America
            %p Plane carrying Pacific Union agents crashes, killing 5 people
            %p The guide to finding the best brokerage near you
            %p Zillow gets broker's license in Arizona
          %span
            .date January 29th
            %p Keller WIlliams award winning voice app Kelle, gets local
            %p Engel and Volkers parts with real estate advisor after DUI arrest, racially charged comments
            %p 5 Ways to calm your seller's nerves when showing listings
            %p The guide to second homes & vacation homes
            %p 12 thank you notes guaranteed to generate leads
            %p Dryer vent do's and dont's
          %span
            .date January 28th
            %p 5 Ways to calm your seller's nerves when showing listings
            %p The guide to second homes & vacation homes
            %p 12 thank you notes guaranteed to generate leads
            %p Dryer vent do's and dont's
      %li
        %span.close-subnav x
        Events
        .second-drop.drop
          %ul.events-wrap
            %li
              %h5 Connect New York 2019
              %h4.event-venue Julliard Center
              %p.event-desc Lorem um quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.
              =link_to("Connect Ny >", "#")
              %span.event-date
                Jul
                %br
                24-29
          %span
            .date January 30th
            %p Connect the Sessions: Get 2019 tips, trends and insights at Hacker Connect
            %p Connect the Sessions: Find your indie advantage at the Indie Broker Summit
            %p Connect the Sessions: Follow the money at Capital Connect
            %p Connect the Sessions: What CMOs need to be building in 2019
          %span
            .date January 29th
            %p Connect the Sessions: Get 2019 tips, trends and insights at Hacker Connect
            %p Connect the Sessions: Find your indie advantage at the Indie Broker Summit
            %p Connect the Sessions: Follow the money at Capital Connect
            %p Connect the Sessions: What CMOs need to be building in 2019
          %span
            .date January 28th
            %p Connect the Sessions: Get 2019 tips, trends and insights at Hacker Connect
            %p Connect the Sessions: Find your indie advantage at the Indie Broker Summit
            %p Connect the Sessions: Follow the money at Capital Connect
            %p Connect the Sessions: What CMOs need to be building in 2019


      %li
        %span.close-subnav x
        The Weekender
        .third-drop.drop
          %span
            %p Zillow to acquire Mortgage Lenders of America
            %p Plane carrying Pacific Union agents crashes, killing 5 people
            %p The guide to finding the best brokerage near you
            %p Zillow gets broker's license in Arizona
            %p Keller WIlliams award winning voice app Kelle, gets local
            %p Engel and Volkers parts with real estate advisor after DUI arrest, racially charged comments
            %p 5 Ways to calm your seller's nerves when showing listings
            %p The guide to second homes & vacation homes
            %p 12 thank you notes guaranteed to generate leads
            %p Dryer vent do's and dont's

app/views/style_guide/colors.html.haml
%h1 StyleGuide#colors
%p Find me in app/views/style_guide/colors.html.erb

app/views/style_guide/imagery.html.haml
%h1 Imagery and Graphics

app/views/style_guide/index.html.haml
=#render 'style_guide/partials/toc_index'

=render 'style_guide/partials/mainColumn_index'

=image_tag "inman-design-logo.png", :width => '120', :class => 'design-logo-main'

-#
  %h1 Typography Guide
  %br
  %section
    %section.article-types
      %h2 Article Types
      %h3
        =link_to 'Standard Article', article_path
      %h3
        =link_to 'Opinion Piece', opinion_path, :class => 'opinion-link'
      %h3
        =link_to 'Service Post', service_path, :class => 'service-link'
      %h3
        =link_to 'Interview', interview_path

    %section.rr-modules
      %h2 Right Rail Modules
      %h3
        =link_to 'Base Module', rr_base_path
      %h3
        =link_to 'Email Sign Up', rr_email_signup_path
    %section.recirculation
      %h2 Article Recirculation
      %h3
        =link_to 'Default Recirculation', recirc_default_path

  %h2 Charts & Graphs

-#
  %h2 Design Explorations(2018)

  %h3
    =link_to "Article Recirculation", "#";

  %h3
    =link_to "Guides UX", design_explorations_guides_path;

  %h3
    =link_to "Unread items menu", design_explorations_new_stories_menu_path;

app/views/style_guide/interview.html.haml
=render 'style_guide/partials/toc_interview'

=render 'style_guide/partials/mainColumn_interview'

app/views/style_guide/logo.html.haml
%h1 logo

app/views/style_guide/opinion.html.haml
=render 'style_guide/partials/toc_opinion'

=render 'style_guide/partials/mainColumn_opinion'

app/views/style_guide/partials/_intro_service.html.haml
.section-wrap
  %h2 overview
  =image_tag "inman-design-logo.png", :width => '120', :class => 'design-logo-main'

  .intro-container
    .welcome-text
      %p
        Headline and font color are the main differentiators for opinion pieces.

      .main-color
        %h3 Main Color
        %p #fc7906
        %p.swatch

    =image_tag "https://coab-alchemy-attachments.s3.amazonaws.com/service-graphic.png", :width => '540'

  .intro-container
    .harriet-sample
      %h3 Harriet
      .alphabet
        %p abcdefghijklm
        %p nopqrstuvwxyz
        %p 0123456789
      .scale
        %span aA
        %span aA
        %span aA
        %span aA
        %span aA
    .balto-sample
      %h3 Balto
      .alphabet
        %p abcdefghijklm
        %p nopqrstuvwxyz
        %p 0123456789
      .scale
        %span aA
        %span aA
        %span aA
        %span aA
        %span aA


  %br

app/views/style_guide/partials/_mainColumn_opinion.html.haml
%section.main-column
  =render 'style_guide/partials/intro_opinion'
  %h1 Opinon Piece
  =render 'style_guide/partials/opinion_typography'

  -#
    %h1 Home Page
    .section-wrap

app/views/style_guide/partials/_mainColumn_orange.html.haml
%section.main-column
  =render 'style_guide/partials/intro_orange'
  %h1 Service Post
  =render 'style_guide/partials/service_typography'
  -#
    %h1 Home Page
    .section-wrap

app/views/style_guide/partials/_mainColumn_service.html.haml
// SERVICES
%section.main-column
  =render 'style_guide/partials/intro_service'
  %h1 Service Post
  =render 'style_guide/partials/service_typography'
  -#
    %h1 Home Page
    .section-wrap

app/views/style_guide/partials/_mainColumn_typography.html.haml
%section.main-column
  =render 'style_guide/partials/intro_typography'
  %h1 Article Post
  =render 'style_guide/partials/article_typography'

app/views/style_guide/partials/_toc_index.html.haml
%section.toc-column
  =link_to '< back', root_path, :class => "back-btn"
  #btn-toggle-mobile
    %span.mobile mobile
    %span.random-line
    %span.random-rectangle
    %span.desktop desktop

  %h1.page-title
    Typography
    %%br
    Guide

app/views/style_guide/partials/_toc_opinion.html.haml
%section.toc-column
  =link_to '< back', root_path, :class => "back-btn"
  #btn-toggle-mobile
    %span.mobile mobile
    %span.random-line
    %span.random-rectangle
    %span.desktop desktop

  %h1.page-title
    Opinion
    %%br
    Typography
  %ul.type-instances
    %li
      Overview

  %h1 Opinion Piece
  %ul.type-instances
    %li
      Head
      %ul.type-group
        %li
          =link_to 'eyebrow','#eyebrow'
        %li
          =link_to 'byline', '#byline'
        %li
          =link_to 'image credit', '#image-credit'
      %li
        Interior
        %ul.type-group
          %li
            =link_to 'highlighted text', '#highlighted-text'
          %li
            =link_to 'pull quote', '#pull-quote'
          %li
            =link_to 'numbered lists', '#numbered-lists'
          %li
            =link_to 'bulleted lists', '#bulleted-lists'

app/views/style_guide/recirc_default.html.haml
=render 'style_guide/partials/toc_recirculation'

=render 'style_guide/partials/mainColumn_recirc'

app/views/style_guide/rr_base.html.haml
=render 'style_guide/partials/toc_rr_base'

=render 'style_guide/partials/mainColumn_rr_base'

app/views/style_guide/story.html.haml
%h1 Story

app/views/style_guide/voice.html.haml
%h1 Voice